name: Composite Lab 1

on:
  workflow_dispatch:
      inputs:
        username:
          description: Enter your name
          required: true
          default: Deepanshu
          type: string
jobs:

  demo:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Run Composite Action
        id: greet
        uses: ./.github/actions/greeting
        with:
          username: ${{ inputs.username }}

      - name: Show Output
        run: |
          echo "Returned:"
          echo "${{ steps.greet.outputs.final_message }}"
