name: "My CICD pipeline"
on: push
jobs:
 hello-ji:
   runs-on: ubuntu-latest
   env: 
     GOD_NAME: "Saraph of the end"
   steps:
     - name: "say hellow"
       run: echo "Hello world this is a pen $GOD_NAME"
