name: Matrix Demo

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment:
          - dev
          - qa
          - prod
        color: [red, blue, green]
        include:
          - color: red
            environment: uat
          - color: red
            environment: blue

    steps:
      - name: Print Environment
        if: ${{ matrix.color == 'red' }}
        run: echo "Deploying to ${{ matrix.environment }}, ${{ matrix.color }}"

      - name: conditional run
        if: ${{matrix.color == 'green' }}
        run: echo "skip"
