name: use organisation level secret
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build for secret
    steps:
      - name: Display secret from org
        run: echo "${{ secrets.MY_ORG_TOKEN }}"

      - name: Display Variables from org
        env:
          VAR_PASS: ${{ vars.MY_ORG_VAR }}
        run: echo "$VAR_PASS"
