name: use organisation level secret
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build for secret
    steps:
      - name: Display secret from org
        run: echo "${{ secrets.MY_ORG_SECRET }}"
