name: My Outputs
on: workflow_dispatch
env:
  TARA: "bankim chandra chatterjee"
jobs:
  build:
    runs-on: windows-latest
    name: namakool_built
    outputs:
      gattu_version: ${{ steps.version.outputs.app_version }}
    steps:
      - name: generate version
        id: version
        shell: pwsh
        run: |
          echo "app_version=1.0.${{ github.run_number }} / ${{ github.repository }} " >> $env:GITHUB_OUTPUT

      - name: show output inside job
        shell: pwsh
        run: |
          echo "Version is ${{steps.version.outputs.app_version}}"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Read output from previous step
        run: |
          echo "Deploying version ${{ needs.build.outputs.gattu_version }}"
        
