name: Reusable work
on: 
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      car:
        required: false
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      CAR: ${{ inputs.car }}
    steps:
      - name: Print both Name and Car
        run: |
          echo "Name: ${{ inputs.name }}
          echo "Car: ${{ inputs.car }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check for Bike in Name
        run: |
          if [[ ${{ inputs.name }} == *bike* ]]; then
            echo "Name contain Bike"
          fi
      - name: Check for Car length in Car
        run: |
          if [${#CAR} -gt 4]; then
            echo "::warning:: Length of car name is too long > 4"
          fi
      
          
    
