name: Setting Env Variable
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: setting env var
        run: echo "FOO=bar" >> $GITHUB_ENV

      - name: using env var
        run: echo "$FOO"
