name: demo workflow run
on:
  workflow_dispatch: 
    inputs:
      test_suit:
        description: This is a pen
        type: choice
        options:
          - functions
          - regression

jobs:
  rahul:
    runs-on: ubuntu-22.04
    name: pokemon pikachu
    run: echo "hello workls:cancel-timeout-minutes: "
